# This is a config for E2B sandbox template.
# You can use template ID (dyotp8abm11rmsx7prm9) or template name (vibe-saas-nextjs-test-2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-saas-nextjs-test-2") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-saas-nextjs-test-2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-saas-nextjs-test-2')

team_id = "52966245-ab7c-4474-9f61-799d623b569f"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-saas-nextjs-test-2"
template_id = "dyotp8abm11rmsx7prm9"
