# This is a config for E2B sandbox template.
# You can use template ID (dyotp8abm11rmsx7prm9) or template name (nextagent-development) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("nextagent-development") # Sync sandbox
# sandbox = await AsyncSandbox.create("nextagent-development") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('nextagent-development')

team_id = "52966245-ab7c-4474-9f61-799d623b569f"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "nextagent-development"
template_id = "dyotp8abm11rmsx7prm9"
